import { Box, Grid, Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import img from '../../public/img/01.svg'
import compImg from '../../public/img/picture.svg'
import compImgMobile from '../../public/img/picture01mobile.svg'
import mobileImg from '../../public/img/01-mobile.svg'
import imgbtn from '../../public/img/mainbtn.png'

import NavigationMenu from '../components/NavigationMenu'
import Reviews from '../components/Reviews'
import Faq3 from '../components/Faq3'
import Faq1 from '../components/Faq1'
import Faq2 from '../components/Faq2'
import Faq4 from '../components/Faq4'
import Faq5 from '../components/Faq5'
import Faq6 from '../components/Faq6'

//motion
import { motion, useAnimation } from 'framer-motion'
import { useInView } from 'react-intersection-observer'
import { useEffect } from 'react'
import { mainMobilePicVariant, rightVariant, topVariant } from '../framer/variants'


const Home: NextPage = () => {

  const controls = useAnimation()
  const [ref, inView] = useInView()

  useEffect(() => {
    if (inView) {
      controls.start("visible");
    }
  }, [controls, inView]);

  return (
      <Box>
        <Head>
          <title>Landing</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/icon?family=Material+Icons"
          />
          <link rel="preload" href='/fonts/Jost/Jost-Regular.ttf' as="font" crossOrigin=""/>
          <link rel="preload" href='/fonts/K2D/K2D-Medium.ttf' as="font" crossOrigin=""/>
          <link rel="preload" href='/fonts/Josefin_Sans/JosevinSans-Regular.ttf' as="font" crossOrigin=""/>
        </Head>
        <Grid container>
          <Grid item xs={12}>
            <NavigationMenu/>
          </Grid>
        </Grid>

        <Grid container>
          <Grid item xs={12} md={12} lg={12}>
            <Box
              sx={{
                '@media screen and (max-width: 980px)': {
                  display: 'none'
                }
              }}
            >
              <Box
                sx={{
                  position: 'absolute',
                  top: 0,
                  right: 0,
                  width: '59.6vw',
                  // height: '50%'
                }}
              >
                <Image src={img} />
              </Box>

              <Box
                sx={{
                  position: 'absolute',
                  top: '8vh',
                  right: 0,
                  // width: '59.6vw',
                  // height: '50%',
                  '@media screen and (max-width: 1600px)': {
                    top: '5vh',
                    right: '5vh',
                  }
                }}
              >
                <motion.div
                  ref={ref}
                  initial="hidden"
                  animate={controls}
                  variants={rightVariant}
                  whileInView="visible"
                  viewport={{once: true}}
                >
                  <Image src={compImg} />
                </motion.div>
              </Box>
            </Box>

            <Box
              sx={{
                display: 'none',
                '@media screen and (max-width: 480px)': {
                  display: 'block',
                  position: 'absolute',
                  top: 0,
                  left: 0
                }
              }}
            >
              <motion.div
                ref={ref}
                initial="hidden"
                animate={controls}
                variants={mainMobilePicVariant}
                whileInView="visible"
                viewport={{once: true}}
              >
                <Image src={mobileImg} />
              </motion.div>
            </Box>
            <Box
              sx={{
                display: 'none',
                '@media screen and (max-width: 480px)': {
                  display: 'block',
                  position: 'absolute',
                  top: '100px',
                  left: 0
                }
              }}
            >
              <motion.div
                  ref={ref}
                  initial="hidden"
                  animate={controls}
                  variants={topVariant}
                  whileInView="visible"
                  viewport={{once: true}}
                >
                  <Image src={compImgMobile} />
                </motion.div>
            </Box>

            <Box
              sx={{
                ml: '98px', 
                mr: '98px', 
                pt: '155px',
                pb: '150px',
                '@media screen and (max-width: 1600px)': {
                  pt: '130px',
                },
                '@media screen and (max-width: 480px)': {
                  ml: '30px',
                  mr: '30px',
                  pt: '400px'
                }
              }}
            >
              <Box
                sx={{
                  display: 'flex',
                }}
              >
                <Box
                  sx={{
                    display: 'flex',
                    flexDirection: 'column',
                    '@media screen and (min-width: 480px)':{
                      width: '958px'
                    }
                  }}
                >
                  <Box
                    sx={{
                      '@media screen and (max-width: 1600px) and (min-width: 768px)': {
                        width: '650px'
                      },
                      '@media screen and (max-width: 480px)': {
                        width: '350px',
                        position: 'relative',
                        zIndex: 2
                      }
                    }}
                  >
                    <Typography
                      sx={{
                        fontWeight: 700,
                        fontSize: '63px',
                        color: '#ffffff',
                        fontFamily: 'K2D',
                        '@media screen and (max-width: 1600px)': {
                          fontSize: '43px'
                        },
                        '@media screen and (max-width: 480px)': {
                          fontSize: '29px'
                        }
                      }}
                    >
                      Stop paying affiliate networks for your brand's organic 
                      search traffic!
                    </Typography>
                  </Box>
                  <Box
                    sx={{
                      width: '800px',
                      pt: '38px',
                      position: 'relative',
                      zIndex: 2,
                      '@media screen and (max-width: 480px)': {
                        width: '350px'
                      },
                      '@media screen and (min-width: 768px) and (max-width: 980px)': {
                        width: '650px'
                      },
                    }}
                  >
                    <Typography
                      sx={{
                        fontSize: '30px',
                        color: '#ffffff',
                        fontFamily: 'Josefin Sans',
                        '@media screen and (max-width: 480px)': {
                          fontSize: '18px'
                        }
                      }}
                    >
                      We help advertisers track webmasters who are attracting contextual traffic to their brand through affiliate networks.
                    </Typography>
                  </Box>
                  <Box
                    sx={{
                      display: 'flex',
                      flexDirection: 'row',
                      alignItems: 'center',
                      margin: '0 -5px',
                      pt: '55px',
                      cursor: 'pointer',
                      '@media screen and (max-width: 480px)': {
                        pb: '80px'
                      }
                    }}
                  >
                    <Box
                      sx={{
                        margin: '0 5px',
                        '@media screen and (max-width: 1600px)': {
                          width: '67px',
                          height: '83px'
                        },
                        '@media screen and (max-width: 480px)': {
                          width: '64px',
                          height: '76px'
                        }
                      }}
                    >
                      <Image src={imgbtn} width={87} height={103} />
                    </Box>
                    <Box
                      sx={{
                        margin: '0 5px'
                      }}
                    >
                      <Typography
                        sx={{
                          fontFamily: 'Jost',
                          color: '#00FF66',
                          fontSize: '48px',
                          '@media screen and (max-width: 1600px)': {
                            fontSize: '30px'
                          },
                          '@media screen and (max-width: 480px)': {
                            fontSize: '35px'
                          }
                        }}
                      >
                        Request a demo
                      </Typography>
                    </Box>
                  </Box>
                </Box>
              </Box>
            </Box>
          </Grid>
          <Grid item xs={12} md={12} lg={12}>
            <Reviews />
          </Grid>
          <Grid item xs={12} md={12} lg={12}>
            <Faq1 />
          </Grid>
          <Grid item xs={12} md={12} lg={12}>
            <Faq2 />
          </Grid>
          <Grid item xs={12} md={12} lg={12}>
            <Faq3 />
          </Grid>
          <Grid item xs={12} md={12} lg={12}>
            <Faq4 />
          </Grid>
          <Grid item xs={12} md={12} lg={12}>
            <Faq5 />
          </Grid>
          <Grid item xs={12} md={12} lg={12}>
            <Faq6 />
          </Grid>
        </Grid>
      </Box>
  )
}

export default Home
