import Box from '@mui/material/Box'
import Head from 'next/head'
import React, { useEffect } from 'react'
import Image from 'next/image'

import img from '../../public/img/faq1.svg'
import compImg from '../../public/img/faq1comp.svg'
import imgbtn from '../../public/img/mainbtn.png'
import mobileImg from '../../public/img/faq1mobile.svg'
import picMobile from '../../public/img/picture03mobile.svg'
import Typography from '@mui/material/Typography'

//motion
import { motion, useAnimation } from 'framer-motion'
import { useInView } from 'react-intersection-observer'
import { mainMobilePicVariant, rightVariant } from '../framer/variants'

const Faq1 = () => {

    const controls = useAnimation()
    const [ref, inView] = useInView()

    useEffect(() => {
        if (inView) {
        controls.start("visible");
        }
    }, [controls, inView]);

    return(
        <>
            <Head>
                <title>FAQ</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link
                rel="stylesheet"
                href="https://fonts.googleapis.com/icon?family=Material+Icons"
                />
                <link rel="preload" href='/fonts/Jost/Jost-Regular.ttf' as="font" crossOrigin=""/>
                <link rel="preload" href='/fonts/K2D/K2D-Medium.ttf' as="font" crossOrigin=""/>
                <link rel="preload" href='/fonts/Josefin_Sans/JosevinSans-Regular.ttf' as="font" crossOrigin=""/>
            </Head>

            <Box
                sx={{
                    '@media screen and (max-width: 980px)': {
                    display: 'none'
                    }
                }}
                >
                <Box
                    sx={{
                    position: 'absolute',
                    top: '280%',
                    right: 0,
                    width: '59.6vw',
                    // height: '50%'
                    '@media screen and (max-width: 1600px)': {
                        top: '340%'
                    },
                    '@media screen and (min-width: 980px) and (max-width: 1366px)': {
                        top: '270%'
                    }
                    }}
                >
                    <Image src={img} />
                </Box>

                <Box
                    sx={{
                    position: 'absolute',
                    top: '310%',
                    right: 0,
                    // width: '59.6vw',
                    // height: '50%',
                    '@media screen and (max-width: 1600px)': {
                        top: '370%',
                        // left: '5vw',
                    },
                    '@media screen and (min-width: 980px) and (max-width: 1366px)': {
                        top: '282%'
                    }
                    }}
                >
                    <motion.div
                        ref={ref}
                        initial="hidden"
                        animate={controls}
                        variants={rightVariant}
                        whileInView="visible"
                        viewport={{once: true}}
                    >
                        <Image src={compImg} />
                    </motion.div>
                </Box>
            </Box>

            <Box
                sx={{
                display: 'none',
                '@media screen and (max-width: 480px)': {
                    display: 'block',
                    position: 'absolute',
                    top: '295%',
                    left: 0
                }
                }}
            >
                <motion.div
                    ref={ref}
                    initial="hidden"
                    animate={controls}
                    variants={mainMobilePicVariant}
                    whileInView="visible"
                    viewport={{once: true}}
                    >
                    <Image src={mobileImg} />
                    </motion.div>
            </Box>
            <Box
                sx={{
                display: 'none',
                '@media screen and (max-width: 480px)': {
                    display: 'block',
                    position: 'absolute',
                    top: '300%',
                    width: '85vw',
                    left: 0
                }
                }}
            >
                <motion.div
                  ref={ref}
                  initial="hidden"
                  animate={controls}
                  variants={rightVariant}
                  whileInView="visible"
                  viewport={{once: true}}
                >
                  <Image src={compImg} />
                </motion.div>
            </Box>

            <Box
                sx={{
                    ml: '98px', 
                    mr: '98px', 
                    pt: '98px',
                    '@media screen and (max-width: 1600px)': {
                      pt: '68px'
                    },
                    '@media screen and (max-width: 480px)': {
                      ml: '30px',
                      mr: '25px',
                      pt: '250px'
                    }
                }}
            >
                <Box
                    sx={{
                        display: 'flex',
                        flexDirection: 'column',
                        justifyContent: 'flex-start',
                    }}
                >
                    <Box
                        sx={{
                            display: 'flex',
                            flexDirection: 'column',
                            alignItems: 'flex-start',
                            // gap: '329px'
                        }}
                    >
                        <Box
                            sx={{
                                '@media screen and (min-width: 980px)': {
                                  width: '939px'
                                },
                                '@media screen and (max-width: 1600px) and (min-width: 980px)': {
                                  width: '650px'
                                },
                                '@media screen and (min-width: 768px) and (max-width: 980px)':{
                                  width: '550px'
                                },
                                '@media screen and (max-width: 480px)': {
                                  width: '345px',
                                  position: 'relative',
                                  zIndex: 2
                                }
                            }}
                        >
                            <Typography
                                sx={{
                                    fontWeight: 700,
                                    fontSize: '43px',
                                    color: '#ffffff',
                                    fontFamily: 'K2D',
                                    '@media screen and (max-width: 480px)': {
                                        fontSize: '29px'
                                    }
                                }}
                            >
                                When can you potenttily face
                            </Typography>
                        </Box>
                        <Box
                            sx={{
                                display: 'flex',
                                flexDirection: 'row',
                                alignItems: 'center',
                                justifyContent: 'space-between',
                                mt: '44px',
                                width: '916px',
                                '@media screen and (min-width: 768px) and (max-width: 980px)': {
                                    width: '550px',
                                    // justifyContent: 'flex-start'
                                },
                                '@media screen and (max-width: 480px)': {
                                    width: '350px',
                                },
                            }}
                        >
                            <Box>
                                <Typography
                                    sx={{
                                        fontSize: '40px',
                                        fontFamily: 'Josefin Sans',
                                        color: '#00FF66',
                                        '@media screen and (min-width: 320px) and (max-width: 980px)': {
                                            fontSize: '24px'
                                        }
                                    }}
                                >
                                    Problems
                                </Typography>
                            </Box>
                            <Box
                                sx={{
                                    width: '581px',
                                    height: '180px',
                                    position: 'relative',
                                    zIndex: 2,
                                    '@media screen and (min-width: 320px) and (max-width: 980px)': {
                                        width: '330px',
                                        height: '220px',
                                        pl: '20px'
                                    }
                                }}
                            >
                                <Typography
                                    sx={{
                                        fontSize: '30px',
                                        fontFamily: 'Josefin Sans',
                                        color: '#ffffff',
                                        '@media screen and (min-width: 320px) and (max-width: 980px)': {
                                            fontSize: '18px'
                                        }
                                    }}
                                >
                                    Such webmasters realise that they are working with a banned traffic source. Thus, they try to hide it in every way possible, for example, by using geotargeting, different devices, and more.
                                </Typography>
                            </Box>
                        </Box>
                        <Box
                            sx={{
                                display: 'flex',
                                flexDirection: 'row',
                                alignItems: 'center',
                                justifyContent: 'space-between',
                                mt: '82px',
                                width: '916px',
                                '@media screen and (min-width: 768px) and (max-width: 980px)': {
                                    width: '550px',
                                    // justifyContent: 'flex-start'
                                },
                                '@media screen and (max-width: 480px)': {
                                    width: '350px'
                                }
                            }}
                        >
                            <Box>
                                <Typography
                                    sx={{
                                        fontSize: '40px',
                                        fontFamily: 'Josefin Sans',
                                        color: '#00FF66',
                                        '@media screen and (min-width: 320px) and (max-width: 980px)': {
                                            fontSize: '24px'
                                        }
                                    }}
                                >
                                    Challenges
                                </Typography>
                            </Box>
                            <Box
                                sx={{
                                    width: '581px',
                                    height: '180px',
                                    position: 'relative',
                                    zIndex: 2,
                                    '@media screen and (min-width: 320px) and (max-width: 980px)': {
                                        width: '330px',
                                        height: '220px',
                                        pl: '20px'
                                    }
                                }}
                            >
                                <Typography
                                    sx={{
                                        fontSize: '30px',
                                        fontFamily: 'Josefin Sans',
                                        color: '#ffffff',
                                        '@media screen and (min-width: 320px) and (max-width: 980px)': {
                                            fontSize: '18px'
                                        }
                                    }}
                                >
                                    To filter out such traffic effectively, you need to monitor your branded search results 24/7 from different devices, regions, different times of the day, IP addresses, etc.
                                </Typography>
                            </Box>
                        </Box>
                        <Box
                            sx={{
                                display: 'flex',
                                flexDirection: 'row',
                                alignItems: 'center',
                                justifyContent: 'space-between',
                                mt: '82px',
                                width: '916px',
                                '@media screen and (min-width: 768px) and (max-width: 980px)': {
                                    width: '550px',
                                    // justifyContent: 'flex-start'
                                },
                                '@media screen and (max-width: 480px)': {
                                    width: '350px'
                                }
                            }}
                        >
                            <Box>
                                <Typography
                                    sx={{
                                        fontSize: '40px',
                                        fontFamily: 'Josefin Sans',
                                        color: '#00FF66',
                                        '@media screen and (min-width: 320px) and (max-width: 980px)': {
                                            fontSize: '24px'
                                        }
                                    }}
                                >
                                    Risks
                                </Typography>
                            </Box>
                            <Box
                                sx={{
                                    width: '581px',
                                    height: '180px',
                                    '@media screen and (min-width: 320px) and (max-width: 980px)': {
                                        width: '330px',
                                        height: '220px',
                                        pl: '20px'
                                    }
                                }}
                            >
                                <Typography
                                    sx={{
                                        fontSize: '30px',
                                        fontFamily: 'Josefin Sans',
                                        color: '#ffffff',
                                        position: 'relative',
                                        zIndex: 2,
                                        '@media screen and (min-width: 320px) and (max-width: 980px)': {
                                            fontSize: '18px'
                                        }
                                    }}
                                >
                                    It is almost impossible to do it manually and sifting out such traffic by behavioural factors, you risk cutting off diligent and conscientious webmasters.
                                </Typography>
                            </Box>
                        </Box>
                        <Box
                            sx={{
                            display: 'flex',
                            flexDirection: 'row',
                            alignItems: 'center',
                            margin: '0 -5px',
                            pt: '55px',
                            cursor: 'pointer',
                            '@media screen and (max-width: 480px)': {
                                pb: '80px'
                            }
                            }}
                        >
                            <Box
                            sx={{
                                margin: '0 5px',
                                '@media screen and (max-width: 1600px)': {
                                width: '67px',
                                height: '83px'
                                },
                                '@media screen and (max-width: 480px)': {
                                width: '64px',
                                height: '76px'
                                }
                            }}
                            >
                            <Image src={imgbtn} width={87} height={103} />
                            </Box>
                            <Box
                            sx={{
                                margin: '0 5px'
                            }}
                            >
                            <Typography
                                sx={{
                                fontFamily: 'Jost',
                                color: '#00FF66',
                                fontSize: '48px',
                                '@media screen and (max-width: 1600px)': {
                                    fontSize: '30px'
                                },
                                '@media screen and (max-width: 480px)': {
                                    fontSize: '35px'
                                }
                                }}
                            >
                                Request a demo
                            </Typography>
                            </Box>
                        </Box>
                    </Box>
                </Box>
            </Box>
        </>
    )
}

export default Faq1