import { Typography } from '@mui/material'
import Box from '@mui/material/Box'
// import { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect } from 'react'
// import NavigationMenu from '../components/NavigationMenu'

import img from '../../public/img/03.svg'
import compImg from '../../public/img/picture03.svg'
import listImg from '../../public/img/icon.svg'
import imgbtn from '../../public/img/mainbtn.png'
import mobileImg from '../../public/img/03-mobile.svg'
import picMobile from '../../public/img/picture03mobile.svg'
import { motion, useAnimation } from 'framer-motion'
import { useInView } from 'react-intersection-observer'
import { leftVariant, mainMobilePicVariant } from '../framer/variants'

const Faq3 = () => {

  const controls = useAnimation()
  const [ref, inView] = useInView()

  useEffect(() => {
    if (inView) {
      controls.start("visible");
    }
  }, [controls, inView]);

  return (
    <>
      <Head>
        <title>FAQ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <link rel="preload" href='/fonts/Jost/Jost-Regular.ttf' as="font" crossOrigin=""/>
        <link rel="preload" href='/fonts/K2D/K2D-Medium.ttf' as="font" crossOrigin=""/>
        <link rel="preload" href='/fonts/Josefin_Sans/JosevinSans-Regular.ttf' as="font" crossOrigin=""/>
      </Head>

      {/* <NavigationMenu /> */}

      <Box
          sx={{
            '@media screen and (max-width: 980px)': {
              display: 'none'
            }
          }}
        >
          <Box
            sx={{
              position: 'absolute',
              top: '527%',
              left: 0,
              width: '59.6vw',
              // height: '50%'
              '@media screen and (max-width: 1600px)': {
                top: '657%'
              },
              '@media screen and (min-width: 980px) and (max-width: 1366px)': {
                   top: '520%' 
              }
            }}
          >
            <Image src={img} />
          </Box>

          <Box
            sx={{
              position: 'absolute',
              top: '555%',
              left: '7vw',
              // width: '59.6vw',
              // height: '50%',
              '@media screen and (max-width: 1600px)': {
                top: '685%',
                left: '5vw',
              },
              '@media screen and (min-width: 980px) and (max-width: 1366px)': {
                top: '540%'
              }
            }}
          >
            <motion.div
              ref={ref}
              initial="hidden"
              animate={controls}
              variants={leftVariant}
              whileInView="visible"
              viewport={{once: true}}
            >
              <Image src={compImg} />
            </motion.div>
          </Box>
      </Box>

      <Box
        sx={{
          display: 'none',
          '@media screen and (max-width: 480px)': {
            display: 'block',
            position: 'absolute',
            top: '646%',
            left: 0
          }
        }}
      >
        <motion.div
          ref={ref}
          initial="hidden"
          animate={controls}
          variants={mainMobilePicVariant}
          whileInView="visible"
          viewport={{once: true}}
        >
          <Image src={mobileImg} />
        </motion.div>
      </Box>
      <Box
        sx={{
          display: 'none',
          '@media screen and (max-width: 480px)': {
            display: 'block',
            position: 'absolute',
            top: '650%',
            left: 0
          }
        }}
      >
        <motion.div
                  ref={ref}
                  initial="hidden"
                  animate={controls}
                  variants={leftVariant}
                  whileInView="visible"
                  viewport={{once: true}}
                >
                  <Image src={picMobile} />
                </motion.div>
      </Box>

      <Box
        sx={{
          ml: '98px', 
          mr: '98px', 
          pt: '250px',
          '@media screen and (max-width: 1600px)': {
            pt: '250px'
          },
          '@media screen and (max-width: 480px)': {
            ml: '30px',
            mr: '25px',
            pt: '550px'
          }
        }}
      >
        <Box
          sx={{
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'flex-end',
            textAlign: 'right'
          }}
        >
          <Box
            sx={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'flex-end',
            }}
          >
            <Box
              sx={{
                '@media screen and (min-width: 980px)': {
                  width: '939px'
                },
                '@media screen and (max-width: 1600px) and (min-width: 980px)': {
                  width: '650px'
                },
                '@media screen and (min-width: 768px) and (max-width: 980px)':{
                  width: '550px'
                },
                '@media screen and (max-width: 480px)': {
                  width: '345px',
                  position: 'relative',
                  zIndex: 2
                }
              }}
            >
              <Typography
                sx={{
                  fontWeight: 700,
                  fontSize: '43px',
                  color: '#ffffff',
                  fontFamily: 'K2D',
                  '@media screen and (max-width: 480px)': {
                    fontSize: '29px'
                  }
                }}
              >
                How can BluePear help your business?
              </Typography>
            </Box>
            <Box
              sx={{
                display: 'flex',
                flexDirection: 'row',
                alignItems: 'center',
                mt: '44px'
              }}
            >
              <Box
                sx={{
                  width: '138px',
                  height: '103px',
                  '@media screen and (max-width: 1600px)': {
                    width: '108px',
                    height: '73px'
                  },
                  '@media screen and (min-width: 768px) and (max-width: 980px)':{
                    width: '82px',
                    height: '62px'
                  },
                  '@media screen and (max-width: 480px)': {
                    width: '82px',
                    height: '62px'
                  }
                }}
              >
                <Image src={listImg} />
              </Box>
              <Box
                sx={{
                  pl: '3vw',
                  width: '916px',
                  '@media screen and (max-width: 1600px)': {
                    width: '650px',
                  },
                  '@media screen and (min-width: 768px) and (max-width: 980px)':{
                    width: '550px'
                  },
                  '@media screen and (max-width: 480px)': {
                    width: '280px'
                  }
                }}
              >
                <Typography
                  sx={{
                    fontSize: '30px',
                    color: '#ffffff',
                    textAlign: 'left',
                    fontFamily: 'Josefin Sans',
                    '@media screen and (max-width: 480px)': {
                      fontSize: '18px'
                    }
                  }}
                >
                  BluePear monitors your branded search queries 24 hours a day, automatically, across all device types, geos, terms and conditions.
                </Typography>
              </Box>
            </Box>
            <Box
              sx={{
                display: 'flex',
                flexDirection: 'row',
                alignItems: 'center',
                mt: '59px'
              }}
            >
              <Box
                sx={{
                  width: '138px',
                  height: '103px',
                  '@media screen and (max-width: 1600px)': {
                    width: '108px',
                    height: '73px'
                  },
                  '@media screen and (min-width: 768px) and (max-width: 980px)':{
                    width: '82px',
                    height: '62px'
                  },
                  '@media screen and (max-width: 480px)': {
                    width: '82px',
                    height: '62px'
                  }
                }}
              >
                <Image src={listImg} />
              </Box>
              <Box
                sx={{
                  pl: '3vw',
                  width: '916px',
                  '@media screen and (max-width: 1600px)': {
                    width: '650px',
                  },
                  '@media screen and (min-width: 768px) and (max-width: 980px)':{
                    width: '550px'
                  },
                  '@media screen and (max-width: 480px)': {
                    width: '280px'
                  }
                }}
              >
                <Typography
                  sx={{
                    fontSize: '30px',
                    color: '#ffffff',
                    textAlign: 'left',
                    fontFamily: 'Josefin Sans',
                    '@media screen and (max-width: 480px)': {
                      fontSize: '18px'
                    }
                  }}
                >
                  Prepares a report for you with the publisher IDs and screenshots of its ads for your branded queries.
                </Typography>
              </Box>
            </Box>
            <Box
              sx={{
                display: 'flex',
                flexDirection: 'row',
                alignItems: 'center',
                mt: '59px'
              }}
            >
              <Box
                sx={{
                  width: '138px',
                  height: '103px',
                  '@media screen and (max-width: 1600px)': {
                    width: '108px',
                    height: '73px'
                  },
                  '@media screen and (min-width: 768px) and (max-width: 980px)':{
                    width: '82px',
                    height: '62px'
                  },
                  '@media screen and (max-width: 480px)': {
                    width: '82px',
                    height: '62px'
                  }
                }}
              >
                <Image src={listImg} />
              </Box>
              <Box
                sx={{
                  pl: '3vw',
                  width: '916px',
                  '@media screen and (max-width: 1600px)': {
                    width: '650px',
                  },
                  '@media screen and (min-width: 768px) and (max-width: 980px)':{
                    width: '550px'
                  },
                  '@media screen and (max-width: 480px)': {
                    width: '280px'
                  }
                }}
              >
                <Typography
                  sx={{
                    fontSize: '30px',
                    color: '#ffffff',
                    textAlign: 'left',
                    fontFamily: 'Josefin Sans',
                    '@media screen and (max-width: 480px)': {
                      fontSize: '18px'
                    }
                  }}
                >
                  This is a proof argument in the dispute with the affiliate network about the quality of the incoming traffic - you will no longer pay the affiliate network for your organic traffic
                </Typography>
              </Box>
            </Box>
          </Box>
          <Box
            sx={{
              display: 'flex',
              flexDirection: 'row',
              justifyContent: 'flex-end',
              mb: '200px',
              '@media screen and (min-width: 768px) and (max-width: 980px)':{
                justifyContent: 'center',
                mb: '50px'
              },
              '@media screen and (max-width: 480px)': {
                justifyContent: 'center',
                mb: '50px'
              }
            }}
          >
            <Box
              sx={{
                display: 'flex',
                flexDirection: 'row',
                alignItems: 'center',
                margin: '0 -5px',
                pt: '55px',
                cursor: 'pointer'
              }}
            >
              <Box
                sx={{
                  margin: '0 5px',
                  '@media screen and (max-width: 1600px)': {
                    width: '67px',
                    height: '83px'
                  },
                  '@media screen and (max-width: 480px)': {
                    width: '64px',
                    height: '76px'
                  }
                }}
              >
                <Image src={imgbtn} width={87} height={103} />
              </Box>
              <Box
                sx={{
                  margin: '0 5px'
                }}
              >
                <Typography
                  sx={{
                    color: '#00FF66',
                    fontSize: '48px',
                    fontFamily: 'Jost',
                    '@media screen and (max-width: 1600px)': {
                      fontSize: '30px'
                    },
                    '@media screen and (max-width: 480px)': {
                      fontSize: '35px'
                    }
                  }}
                >
                  Request a demo
                </Typography>
              </Box>
            </Box>
          </Box>
        </Box>
      </Box>
    </>
  )
}

export default Faq3