import { Box, Slider, Tooltip, Typography } from '@mui/material'
import { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect, useState } from 'react'
// import NavigationMenu from '../components/NavigationMenu'


import img from '../../public/img/02.svg'
import compImg from '../../public/img/picture02.svg'
import mobileImg from '../../public/img/02-mobile.svg'
import picMobile from '../../public/img/picture02mobile.svg'

//motion
import { leftVariant, mainMobilePicVariant } from '../framer/variants'
import { motion, useAnimation } from "framer-motion"
import { useInView } from 'react-intersection-observer'

const Reviews = () => {

  const controls = useAnimation()
  const [ref, inView] = useInView()

  useEffect(() => {
    if (inView) {
      controls.start("visible");
      console.log("working")
    }
  }, [controls, inView]);

  const [valueOne, setValueOne] = useState<number>(0)
  const [valueTwo, setValueTwo] = useState<number>(0)

  const handleChangeOne = (event: Event, newValue: number | number[]) => {
    if (typeof newValue === 'number') {
      setValueOne(newValue);
    }
  }

  const handleChangeTwo = (event: Event, newValue: number | number[]) => {
    if (typeof newValue === 'number') {
      setValueTwo(newValue);
    }
  }

  return (
    <>
      <Head>
        <title>Reviews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <link rel="preload" href='/fonts/Jost/Jost-Regular.ttf' as="font" crossOrigin=""/>
        <link rel="preload" href='/fonts/K2D/K2D-Medium.ttf' as="font" crossOrigin=""/>
        <link rel="preload" href='/fonts/Josefin_Sans/JosevinSans-Regular.ttf' as="font" crossOrigin=""/>
      </Head>

      {/* <NavigationMenu /> */}

      <Box
          sx={{
            '@media screen and (max-width: 980px)': {
              display: 'none'
            }
          }}
        >
          <Box
            sx={{
              position: 'absolute',
              top: '100%',
              left: 0,
              width: '59.6vw',
            }}
          >
            <Image src={img} />
          </Box>

          <Box
            sx={{
              position: 'absolute',
              top: '120%',
              left: '10vw',
              '@media screen and (mix-width: 1400px) and (max-width: 1600px)': {
                top: '25vh',
                left: '5vh',
              }
            }}
          >
            <motion.div
              ref={ref}
              initial="hidden"
              animate={controls}
              variants={leftVariant}
              whileInView="visible"
              viewport={{once: true}}
            >
              <Image src={compImg} />
            </motion.div>
            
          </Box>
      </Box>

      <Box
        sx={{
          display: 'none',
          '@media screen and (max-width: 480px)': {
            display: 'block',
            position: 'absolute',
            top: '115%',
            left: 0
          }
        }}
      >
        <motion.div
          ref={ref}
          initial="hidden"
          animate={controls}
          variants={mainMobilePicVariant}
          whileInView="visible"
          viewport={{once: true}}
        >
          <Image src={mobileImg} />
        </motion.div>
      </Box>
      <Box
        sx={{
          display: 'none',
          '@media screen and (max-width: 480px)': {
            display: 'block',
            position: 'absolute',
            top: '120%',
            left: 0
          }
        }}
      >
        <motion.div
                  ref={ref}
                  initial="hidden"
                  animate={controls}
                  variants={leftVariant}
                  whileInView="visible"
                  viewport={{once: true}}
                >
                  <Image src={picMobile} />
                </motion.div>
      </Box>

      <Box
        sx={{
          ml: '98px', 
          mr: '98px', 
          pt: '98px',
          '@media screen and (max-width: 1600px)': {
            pt: '68px'
          },
          '@media screen and (max-width: 480px)': {
            ml: '30px',
            mr: '25px',
            pt: '240px'
          }
        }}
      >
        <Box
          sx={{
            display: 'flex',
            justifyContent: 'flex-end',
            textAlign: 'right',
          }}
        >
          <Box
            sx={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'flex-end',
              // width: '939px',
              '@media screen and (min-width: 480px)': {
                width: '939px'
              }
            }}
          >
            <Box
              sx={{
                '@media screen and (max-width: 1600px) and (min-width: 980px)': {
                  width: '650px'
                },
                '@media screen and (min-width: 768px) and (max-width: 980px)':{
                  width: '550px'
                },
                '@media screen and (max-width: 480px)': {
                  width: '350px',
                  position: 'relative',
                  zIndex: 2
                }
              }}
            >
              <Typography
                sx={{
                  fontWeight: 700,
                  fontSize: '63px',
                  color: '#ffffff',
                  fontFamily: 'K2D',
                  '@media screen and (max-width: 1600px)': {
                    fontSize: '43px'
                  },
                  '@media screen and (max-width: 480px)': {
                    fontSize: '29px'
                  }
                }}
              >
                Calculate how much traffic and money you are losing
              </Typography>
            </Box>
            <Box
              sx={{
                '@media screen and (max-width: 1600px)': {
                  width: '650px'
                },
                '@media screen and (min-width: 768px) and (max-width: 980px)':{
                  width: '550px'
                },
                pt: '38px',
                position: 'relative',
                zIndex: 2,
                '@media screen and (max-width: 480px)': {
                  width: '350px'
                }
              }}
            >
              <Typography
                sx={{
                  fontSize: '30px',
                  color: '#ffffff',
                  fontFamily: 'Josefin Sans',
                  '@media screen and (max-width: 480px)': {
                    fontSize: '18px'
                  }
                }}
              >
                Large companies which work with affiliate networks forbid webmasters to drive contextual traffic to the brand. However, black-hat webmasters try to cheat the advertiser and drive traffic to the branded keywords. In the end, the brand is paying the webmaster for its organic traffic!
              </Typography>
            </Box>
            <Box
              sx={{
                height: '236px',
                width: '939px',
                background: 'linear-gradient(180deg, rgba(104, 79, 255, 0.31) 0%, rgba(104, 79, 255, 0) 100%)',
                borderRadius: '11px',
                pt: '54px',
                pb: '54px',
                pl: '66px',
                pr: '66px',
                mt: '38px',
                mb: '125px',
                '@media screen and (max-width: 1600px)': {
                  width: '650px'
                },
                '@media screen and (min-width: 768px) and (max-width: 820px)':{
                  width: '550px'
                },
                '@media screen and (max-width: 480px)': {
                  height: '120px',
                  width: '369px',
                  pt: '25px',
                  pl: '19px',
                  pr: '19px',
                  pb: '25px'
                }
              }}
            >
              <Box
                sx={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  textAlign: 'left'
                }}
              >
                <Box
                  sx={{
                    display: 'flex',
                    flexDirection: 'column'
                  }}
                >
                  <Box>
                    <Typography
                      sx={{
                        fontSize: '20px',
                        color: '#ffffff',
                        fontFamily: 'Josefin Sans',
                        '@media screen and (max-width: 1600px)': {
                          fontSize: '14px'
                        },
                        '@media screen and (max-width: 480px)': {
                          fontSize: '12px'
                        }
                      }}
                    >
                      Affiliate steals from you
                    </Typography>
                  </Box>
                  <Box>
                    <Tooltip 
                      PopperProps={{
                        sx: {
                          "& .MuiTooltip-tooltip": {
                            background: 'linear-gradient(180deg, #00FF66 0%, #00FFF0 100%)',
                            borderRadius: '34px',
                            pl: '40px',
                            pr: '40px',
                            pt: '29px',
                            pb: '8px',
                          }
                        }
                      }}
                      title={
                        <>
                          <Box
                            sx={{
                              display: 'flex',
                              flexDirection: 'column'
                            }}
                          >
                            <Typography
                              sx={{
                                fontWeight: 700,
                                fontFamily: 'Josefin Sans',
                                fontSize: '29px',
                                color: '#000000',
                                textAlign: 'right',
                                '@media screen and (max-width: 1600px)': {
                                  fontSize: '18px'
                                }
                              }}
                            >
                              Too math?
                            </Typography>
                            <Typography
                              sx={{
                                fontSize: '29px',
                                color: '#000000',
                                fontFamily: 'Josefin Sans',
                                '@media screen and (max-width: 1600px)': {
                                  fontSize: '18px'
                                }
                              }}
                            >
                              Text_Text_Text_Text_Text_Text_Text_Text_Text_Text_Text_
                            </Typography>
                          </Box>
                        </>
                      }
                      placement="bottom-end"
                    >
                      <Typography
                        sx={{
                          fontSize: '76px',
                          fontFamily: 'Josefin Sans',
                          color: '#00FF66',
                          '@media screen and (max-width: 1600px)': {
                            fontSize: '56px'
                          },
                          '@media screen and (max-width: 480px)': {
                            fontSize: '35px'
                          }
                        }}
                      >
                        25 000 $
                      </Typography>
                    </Tooltip>
                  </Box>
                  <Box>
                    <Typography
                      sx={{
                        fontSize: '27px',
                        color: '#00FF66',
                        fontFamily: 'Josefin Sans',
                        '@media screen and (max-width: 1600px)': {
                          fontSize: '18px'
                        },
                        '@media screen and (max-width: 480px)': {
                          fontSize: '12px'
                        }
                      }}
                    >
                      With the given CR to sale
                    </Typography>
                  </Box>
                </Box>
                <Box
                  sx={{
                    display: 'flex',
                    flexDirection: 'column'
                  }}
                >
                  <Box>
                    <Typography
                      sx={{
                        fontSize: '20px',
                        color: '#ffffff',
                        fontFamily: 'Josefin Sans',
                        '@media screen and (max-width: 1600px)': {
                          fontSize: '14px'
                        },
                        '@media screen and (max-width: 480px)': {
                          fontSize: '12px'
                        }
                      }}
                    >
                      Affiliate steals from you
                    </Typography>
                  </Box>
                  <Box>
                  <Tooltip 
                      PopperProps={{
                        sx: {
                          "& .MuiTooltip-tooltip": {
                            background: 'linear-gradient(180deg, #00FF66 0%, #00FFF0 100%)',
                            borderRadius: '34px',
                            pl: '40px',
                            pr: '40px',
                            pt: '29px',
                            pb: '8px'
                          }
                        }
                      }}
                      title={
                        <>
                          <Box
                            sx={{
                              display: 'flex',
                              flexDirection: 'column'
                            }}
                          >
                            <Typography
                              sx={{
                                fontWeight: 700,
                                fontSize: '29px',
                                fontFamily: 'Josefin Sans',
                                color: '#000000',
                                textAlign: 'right',
                                '@media screen and (max-width: 1600px)': {
                                  fontSize: '18px'
                                }
                              }}
                            >
                              Too math?
                            </Typography>
                            <Typography
                              sx={{
                                fontSize: '29px',
                                color: '#000000',
                                fontFamily: 'Josefin Sans',
                                '@media screen and (max-width: 1600px)': {
                                  fontSize: '18px'
                                }
                              }}
                            >
                              Text_Text_Text_Text_Text_Text_Text_Text_Text_Text_Text_
                            </Typography>
                          </Box>
                        </>
                      }
                      placement="bottom-end"
                      sx={{
                        '& .css-yem0l2-MuiPopper-root-MuiToolip-popper': {
                          background: 'linear-gradient(180deg, #00FF66 0%, #00FFF0 100%)'
                        }
                      }}
                    >
                      <Typography
                        sx={{
                          fontSize: '76px',
                          color: '#00FF66',
                          fontFamily: 'Josefin Sans',
                          '@media screen and (max-width: 1600px)': {
                            fontSize: '56px'
                          },
                          '@media screen and (max-width: 480px)': {
                            fontSize: '35px'
                          }
                        }}
                      >
                        250
                      </Typography>
                    </Tooltip>
                  </Box>
                  <Box>
                    <Typography
                      sx={{
                        fontSize: '27px',
                        color: '#00FF66',
                        fontFamily: 'Josefin Sans',
                        '@media screen and (max-width: 1600px)': {
                          fontSize: '18px'
                        },
                        '@media screen and (max-width: 480px)': {
                          fontSize: '12px'
                        }
                      }}
                    >
                      With the given CR to sale
                    </Typography>
                  </Box>
                </Box>
              </Box>
            </Box>
            <Box>
              <Box
                sx={{
                  display: 'flex',
                  flexDirection: 'column',
                  width: '939px',
                  '@media screen and (max-width: 1600px)': {
                    width: '650px'
                  },
                  '@media screen and (min-width: 768px) and (max-width: 820px)':{
                    width: '550px'
                  },
                  '@media screen and (max-width: 480px)': {
                    width: '352px',
                  }
                }}
              >
                <Typography
                  sx={{
                    textAlign: 'left',
                    color: '#ffffff',
                    fontSize: '20px',
                    fontFamily: 'Josefin Sans',
                    mb: '15px',
                    '@media screen and (max-width: 480px)': {
                      fontSize: '12px'
                    }
                  }}
                >
                  headline_headline_headline_headlineheadline
                </Typography>
                <Typography
                  sx={{
                    textAlign: 'left',
                    fontSize: '48px',
                    color: '#00FF66',
                    fontFamily: 'Josefin Sans',
                    '@media screen and (max-width: 480px)': {
                      fontSize: '20px'
                    }
                  }}
                >
                  {valueOne}
                </Typography>
              </Box>
              <Box>
                <Slider 
                  size="small"
                  defaultValue={valueOne}
                  max={100000}
                  onChange={handleChangeOne}
                  aria-label="Small"
                  valueLabelDisplay="off"
                />
              </Box>
            </Box>
            <Box
              sx={{
                mt: '73px',
                mb: '400px'
              }}
            >
              <Box
                sx={{
                  display: 'flex',
                  flexDirection: 'column',
                  width: '939px',
                  '@media screen and (max-width: 1600px)': {
                    width: '650px'
                  },
                  '@media screen and (min-width: 768px) and (max-width: 820px)':{
                    width: '550px'
                  },
                  '@media screen and (max-width: 480px)': {
                    width: '352px'
                  }
                }}
              >
                <Typography
                  sx={{
                    textAlign: 'left',
                    color: '#ffffff',
                    fontSize: '20px',
                    fontFamily: 'Josefin Sans',
                    mb: '15px',
                    '@media screen and (max-width: 480px)': {
                      fontSize: '12px'
                    }
                  }}
                >
                  headline_headline_headline_headlineheadline
                </Typography>
                <Typography
                  sx={{
                    textAlign: 'left',
                    fontSize: '48px',
                    color: '#00FF66',
                    fontFamily: 'Josefin Sans',
                    '@media screen and (max-width: 480px)': {
                      fontSize: '20px'
                    }
                  }}
                >
                  {valueTwo}
                </Typography>
              </Box>
              <Box>
                <Slider 
                  size="small"
                  defaultValue={valueTwo}
                  max={8000}
                  onChange={handleChangeTwo}
                  aria-label="Small"
                  valueLabelDisplay="off"
                />
              </Box>
            </Box>
          </Box>
        </Box>
      </Box>

    </>
  )
}

export default Reviews